export const constantApi = {
  // cc
  // fetchLicenseFunctionResource: '/cloudcanal/console/api/v1/inner/constant/fetchlicensefunctionresource',
  // transformJobType: '/cloudcanal/console/api/v1/inner/constant/transformjobtype',
  // listSpecs: '/cloudcanal/console/api/v1/inner/spec/listspecs',
  // listLoopRunTypes: '/cloudcanal/console/api/v1/inner/constant/listloopruntypes',
  // dsCheckReviseOpts: 'cloudcanal/console/api/v1/inner/constant/ds/dscheckreviseopts',
  // cleanTargetBeforeFullDsType: '/cloudcanal/console/api/v1/inner/constant/cleantargetbeforefulldstype',
  // reSchemaMigrationDsType: '/cloudcanal/console/api/v1/inner/constant/reschemamigrationdstype',
  // tableMappingRule: '/cloudcanal/console/api/v1/inner/constant/ds/tablemappingrule',
  // columnMappingRule: '/cloudcanal/console/api/v1/inner/constant/ds/columnmappingrule',
  // noPkUkSyncUpdateDelete: '/cloudcanal/console/api/v1/inner/constant/nopkuksyncupdatedelete',
  // getEsAnalyzerTypes: '/cloudcanal/console/api/v1/inner/constant/getesanalyzertypes',
  // schemaLessValueFormatTemplate: '/cloudcanal/console/api/v1/inner/constant/schemalessvalueformattemplate',
  // listHivePartitionFunc: '/cloudcanal/console/api/v1/inner/constant/listhivepartitionfunc',
  // listHdfsFileFormatAndCompress: '/cloudcanal/console/api/v1/inner/constant/listhdfsfileformatandcompress',
  // polarDbxPartitionAlgs: '/cloudcanal/console/api/v1/inner/constant/dspartition/polardbxpartitionalgs',
  // listVirtualColType: '/cloudcanal/console/api/v1/inner/constant/ds/listvirtualcoltype',
  // specifiedKeysSupport: '/cloudcanal/console/api/v1/inner/constant/ds/specifiedkeyssupport',
  // virtualColGenSupport: '/cloudcanal/console/api/v1/inner/constant/ds/virtualcolgensupport',
  // listVirtualColGenRule: '/cloudcanal/console/api/v1/inner/constant/ds/listvirtualcolgenrule',
  // listTableSelectModes: '/cloudcanal/console/api/v1/inner/constant/listTableSelectModes',
  // listLLMVirtualColType: '/cloudcanal/console/api/v1/inner/constant/ds/listllmvirtualcoltype',
  // listDstVectorSupport: '/cloudcanal/console/api/v1/inner/constant/ds/listdstvectorsupport',
  // listDstChatSupport: '/cloudcanal/console/api/v1/inner/constant/ds/listdstchatsupport',
  // calculateMqPartition: '/cloudcanal/console/api/v1/inner/constant/dspartition/calculatemqpartition',
  listDataTransformScripts: '/cloudcanal/console/api/v1/inner/constant/listDataTransformScripts',
  // dm
  // listRegions: '/clouddm/console/api/v1/constant/region',
  // listRegionAreas: '/clouddm/console/api/v1/constant/listregionareas',
  // listSupportedRegions: '/clouddm/console/api/v1/constant/supportedregion',
  // supportedPushDown: '/cloudcanal/console/api/v1/inner/constant/supportedpushdown',
  // getDeployEnvList: '/clouddm/console/api/v1/constant/listdeployenv',
  // getRegionList: '/clouddm/console/api/v1/constant/listregionbydeploy',
  // getDsTypeList: '/clouddm/console/api/v1/constant/listdstypes',
  // getDsTypeLisrWithoutDeployEnv: '/clouddm/console/api/v1/constant/listdstypeswithoutenv',
  // getDesensitizeRuleTypeList: '/clouddm/console/api/v1/constant/listdesensitizeruletypes',
  // getDsDesensitizePathElements: '/clouddm/console/api/v1/constant/listdsdesensitizepathelements',
  // listPageElementsLevel: '/clouddm/console/api/v1/constant/listPageElementsLevel',
  // listDsSecurityOption: '/clouddm/console/api/v1/constant/listdssecurityoption',
  // listExportSqExecType: '/clouddm/console/api/v1/constant/listexportsqexectype',
  // rdp
  // dsLLMTypes: '/rdp/console/api/v1/constant/ds/dsllmtypes',
  // dsLLMEmbeddingTypes: '/rdp/console/api/v1/constant/ds/dsllmembeddingtypes',
  // dsLLMChatTypes: '/rdp/console/api/v1/constant/ds/dsllmchattypes',
  // listDownloadProduct: '/rdp/console/api/v1/constant/listDownloadProduct',

  // cc
  ccCcGlobalConfig: '/cloudcanal/console/api/v1/inner/cc_global_settings',

  ccConstantTransformJobType: '/cloudcanal/console/api/v1/inner/constant/transformjobtype',
  ccConstantListLoopRunTypes: '/cloudcanal/console/api/v1/inner/constant/listloopruntypes',
  ccConstantCleanTargetBeforeFullDsType: '/cloudcanal/console/api/v1/inner/constant/cleantargetbeforefulldstype',
  ccConstantNoPkUkSyncUpdateDelete: '/cloudcanal/console/api/v1/inner/constant/nopkuksyncupdatedelete',
  ccConstantGetEsAnalyzerTypes: '/cloudcanal/console/api/v1/inner/constant/getesanalyzertypes',
  ccConstantSchemaLessValueFormatTemplate: '/cloudcanal/console/api/v1/inner/constant/schemalessvalueformattemplate',
  ccConstantListHivePartitionFunc: '/cloudcanal/console/api/v1/inner/constant/listhivepartitionfunc',
  ccConstantListHdfsFileFormatAndCompress: '/cloudcanal/console/api/v1/inner/constant/listhdfsfileformatandcompress',
  ccConstantSupportedPushDown: '/cloudcanal/console/api/v1/inner/constant/supportedpushdown',
  ccConstantConsoleJobLabel: '/cloudcanal/console/api/v1/inner/constant/consolejoblabel',
  ccConstantCloudOrIdcName: '/cloudcanal/console/api/v1/inner/constant/cloudoridcname',
  ccConstantWorkerType: '/cloudcanal/console/api/v1/inner/constant/workertype',
  ccConstantRegion: '/cloudcanal/console/api/v1/inner/constant/region',
  ccConstantDataTaskState: '/cloudcanal/console/api/v1/inner/constant/datataskstate',
  ccConstantConsoleTaskState: '/cloudcanal/console/api/v1/inner/constant/consoletaskstate',
  ccConstantSupportedSourceDstype: '/cloudcanal/console/api/v1/inner/constant/supportedsourcedstype',
  ccConstantSupportedTargetDstype: '/cloudcanal/console/api/v1/inner/constant/supportedtargetdstype',
  ccConstantSupportedRegion: '/cloudcanal/console/api/v1/inner/constant/supportedregion',
  ccConstantGlobalConfig: '/cloudcanal/console/api/v1/inner/constant/global/config',
  ccConstantMqSchemaLessValueFormats: '/cloudcanal/console/api/v1/inner/constant/mqschemalessvalueformats',
  ccConstantCacheSchemaLessValueFormats: '/cloudcanal/console/api/v1/inner/constant/cacheschemalessvalueformats',
  ccConstantCkTableEngine: '/cloudcanal/console/api/v1/inner/constant/cktableengine',
  ccConstantSrOrDorisTableModel: '/cloudcanal/console/api/v1/inner/constant/srordoristablemodel',
  ccConstantDsPosTypes: '/cloudcanal/console/api/v1/inner/constant/dspostypes',
  ccConstantEditJobInitialSyncSwitch: '/cloudcanal/console/api/v1/inner/constant/editjobinitialsyncswitch',
  ccConstantNeedTestBeforeAddDsTypes: '/cloudcanal/console/api/v1/inner/constant/needtestbeforeadddstypes',
  ccConstantShowPositionConf: '/cloudcanal/console/api/v1/inner/constant/show_position_conf',
  ccConstantTunnelValueFormats: '/cloudcanal/console/api/v1/inner/constant/tunnelvalueformats',
  ccConstantRdbTargetKeyConflictStrategy: '/cloudcanal/console/api/v1/inner/constant/rdbtargetkeyconflictstrategy',
  ccConstantSchemaQueryTypes: '/cloudcanal/console/api/v1/inner/constant/schemaquerytypes',
  ccConstantSchemaFilterTypes: '/cloudcanal/console/api/v1/inner/constant/schemafiltertypes',
  ccConstantListCountry: '/cloudcanal/console/api/v1/inner/constant/listcountry',
  ccConstantMqOriginalDecodeMsgFormats: '/cloudcanal/console/api/v1/inner/constant/mqorigindecodemsgformats',
  ccConstantSupportSrcDeployTypes: '/cloudcanal/console/api/v1/inner/constant/supportsrcdeploytypes',
  ccConstantSupportDstDeployTypes: '/cloudcanal/console/api/v1/inner/constant/supportdstdeploytypes',
  ccConstantListDataJobKvTemplates: '/cloudcanal/console/api/v1/inner/constant/listdatajobkvtemplates',
  ccConstantListTableWithUks: '/cloudcanal/console/api/v1/inner/constant/listTableWithUks',
  ccConstantReSchemaMigrationDsType: '/cloudcanal/console/api/v1/inner/constant/reschemamigrationdstype',
  ccConstantListTableSelectModes: '/cloudcanal/console/api/v1/inner/constant/listTableSelectModes',

  ccConstantDsDsCheckReviseOpts: 'cloudcanal/console/api/v1/inner/constant/ds/dscheckreviseopts',
  ccConstantDsTableMappingRule: '/cloudcanal/console/api/v1/inner/constant/ds/tablemappingrule',
  ccConstantDsColumnMappingRule: '/cloudcanal/console/api/v1/inner/constant/ds/columnmappingrule',
  ccConstantDsListVirtualColType: '/cloudcanal/console/api/v1/inner/constant/ds/listvirtualcoltype',
  ccConstantDsSpecifiedKeysSupport: '/cloudcanal/console/api/v1/inner/constant/ds/specifiedkeyssupport',
  ccConstantDsVirtualColGenSupport: '/cloudcanal/console/api/v1/inner/constant/ds/virtualcolgensupport',
  ccConstantDsListVirtualColGenRule: '/cloudcanal/console/api/v1/inner/constant/ds/listvirtualcolgenrule',
  ccConstantDsListLLMVirtualColType: '/cloudcanal/console/api/v1/inner/constant/ds/listllmvirtualcoltype',
  ccConstantDsListDstVectorSupport: '/cloudcanal/console/api/v1/inner/constant/ds/listdstvectorsupport',
  ccConstantDsOraInCrMode: '/cloudcanal/console/api/v1/inner/constant/ds/oraincrmode',
  ccConstantDsSchemaMappingRule: '/cloudcanal/console/api/v1/inner/constant/ds/schemamappingrule',
  ccConstantDsListChatSupport: '/cloudcanal/console/api/v1/inner/constant/ds/listchatsupport',
  ccConstantDsListDstEmbeddingSupport: '/cloudcanal/console/api/v1/inner/constant/ds/listdstembeddingsupport',
  ccConstantDsDstDsDdlSupport: '/cloudcanal/console/api/v1/inner/constant/ds/dstDsDdlSupport',
  ccConstantDsLegacyActMapping: '/cloudcanal/console/api/v1/inner/constant/ds/legacyActMapping',

  ccConstantDsPartitionPolarDbxPartitionAlgs: '/cloudcanal/console/api/v1/inner/constant/dspartition/polardbxpartitionalgs',
  ccConstantDsPartitionTdsqlMySQLAlgs: '/cloudcanal/console/api/v1/inner/constant/dspartition/tdsqlmysqlpartitionalgs',
  ccConstantDsPartitionCalculateMqPartition: '/cloudcanal/console/api/v1/inner/constant/dspartition/calculatemqpartition',

  ccConstantDsCharsetDsCharsetOptions: '/cloudcanal/console/api/v1/inner/constant/dscharset/dscharsetoptions',

  ccConstantSpecListSpecs: '/cloudcanal/console/api/v1/inner/spec/listspecs',
  // dm
  dmConstantListRegionAreas: '/clouddm/console/api/v1/constant/listregionareas',
  dmConstantListDeployEnv: '/clouddm/console/api/v1/constant/listdeployenv',
  dmConstantListDsTypes: '/clouddm/console/api/v1/constant/listdstypes',
  dmConstantListDsTypesWithoutEnv: '/clouddm/console/api/v1/constant/listdstypeswithoutenv',
  dmConstantListDesensitizeRuleTypes: '/clouddm/console/api/v1/constant/listdesensitizeruletypes',
  dmConstantListDsDesensitizePathElements: '/clouddm/console/api/v1/constant/listdsdesensitizepathelements',
  dmConstantListPageElementsLevel: '/clouddm/console/api/v1/constant/listPageElementsLevel',
  dmConstantListDsSecurityOption: '/clouddm/console/api/v1/constant/listdssecurityoption',
  dmConstantListExportSqExecType: '/clouddm/console/api/v1/constant/listexportsqexectype',
  dmConstantListDsConnectionOption: '/clouddm/console/api/v1/constant/listdsconnectionoption',

  // rdp
  rdpConstantListRegionAreas: '/rdp/console/api/v1/constant/listregionareas',
  rdpConstantDsSupportedRegion: '/rdp/console/api/v1/constant/dssupportedregion',
  rdpConstantListFilterDsTypes: '/rdp/console/api/v1/constant/listfilterdstypes',
  rdpConstantListDsTypesByDeployType: '/rdp/console/api/v1/constant/listdstypesbydeploytype',

  rdpConstantDsLLMEmbeddingTypes: '/rdp/console/api/v1/constant/ds/dsllmembeddingtypes',
  rdpConstantDsLLMChatTypes: '/rdp/console/api/v1/constant/ds/dsllmchattypes',
  rdpConstantDsSecurityOption: '/rdp/console/api/v1/constant/ds/dssecurityoption',
  rdpConstantDsDsConnectType: '/rdp/console/api/v1/constant/ds/dsconnecttype',
  rdpConstantDsDsLlmEmbeddingTypes: '/rdp/console/api/v1/constant/ds/dsllmembeddingtypes',
  rdpConstantDsDsLlmChatTypes: '/rdp/console/api/v1/constant/ds/dsllmchattypes'
};
