export const financeApi = {
  // userInvoiceApplyCount: '/rdp/console/api/v1/finance/userInvoiceApplyCount',
  // pageListUserInvoiceApply: '/rdp/console/api/v1/finance/pageListUserInvoiceApply',
  // cancelInvoiceApply: '/rdp/console/api/v1/finance/cancelInvoiceApply',
  // modifyInvoiceApply: '/rdp/console/api/v1/finance/modifyInvoiceApply',
  // userUnInvoicedOrderCount: '/rdp/console/api/v1/finance/userUnInvoicedOrderCount',
  // pageListUserUnInvoicedOrder: '/rdp/console/api/v1/finance/pageListUserUnInvoicedOrder',
  // userUnInvoicedMonthlyBillCount: '/rdp/console/api/v1/finance/userUnInvoicedMonthlyBillCount',
  // pageListUserUnInvoicedMonthlyBill: '/rdp/console/api/v1/finance/pageListUserUnInvoicedMonthlyBill',
  // calculateInvoiceAmount: '/rdp/console/api/v1/finance/calculateInvoiceAmount',
  // applyInvoice: '/rdp/console/api/v1/finance/applyInvoice',
  // queryUserBalance: '/rdp/console/api/v1/finance/queryUserBalance',
  // changeBalanceNeedAlert: '/rdp/console/api/v1/finance/changeBalanceNeedAlert',
  // changeAlertBalance: '/rdp/console/api/v1/finance/changeAlertBalance',
  // createPrepay: '/rdp/console/api/v1/finance/createPrepay',
  // payUrlGenForPrepay: '/rdp/console/api/v1/finance/payUrlGenForPrepay',
  // userPrepayCount: '/rdp/console/api/v1/finance/userPrepayCount',
  // pageListUserPrepays: '/rdp/console/api/v1/finance/pageListUserPrepays',
  // cancelPrepay: '/rdp/console/api/v1/finance/cancelPrepay',

  // rdp
  rdpFinanceUserInvoiceApplyCount: '/rdp/console/api/v1/finance/userInvoiceApplyCount',
  rdpFinancePageListUserInvoiceApply: '/rdp/console/api/v1/finance/pageListUserInvoiceApply',
  rdpFinanceCancelInvoiceApply: '/rdp/console/api/v1/finance/cancelInvoiceApply',
  rdpFinanceModifyInvoiceApply: '/rdp/console/api/v1/finance/modifyInvoiceApply',
  rdpFinanceUserUnInvoicedOrderCount: '/rdp/console/api/v1/finance/userUnInvoicedOrderCount',
  rdpFinancePageListUserUnInvoicedOrder: '/rdp/console/api/v1/finance/pageListUserUnInvoicedOrder',
  rdpFinanceUserUnInvoicedMonthlyBillCount: '/rdp/console/api/v1/finance/userUnInvoicedMonthlyBillCount',
  rdpFinancePageListUserUnInvoicedMonthlyBill: '/rdp/console/api/v1/finance/pageListUserUnInvoicedMonthlyBill',
  rdpFinanceCalculateInvoiceAmount: '/rdp/console/api/v1/finance/calculateInvoiceAmount',
  rdpFinanceApplyInvoice: '/rdp/console/api/v1/finance/applyInvoice',
  rdpFinanceQueryUserBalance: '/rdp/console/api/v1/finance/queryUserBalance',
  rdpFinanceChangeBalanceNeedAlert: '/rdp/console/api/v1/finance/changeBalanceNeedAlert',
  rdpFinanceChangeAlertBalance: '/rdp/console/api/v1/finance/changeAlertBalance',
  rdpFinanceCreatePrepay: '/rdp/console/api/v1/finance/createPrepay',
  rdpFinancePayUrlGenForPrepay: '/rdp/console/api/v1/finance/payUrlGenForPrepay',
  rdpFinanceUserPrepayCount: '/rdp/console/api/v1/finance/userPrepayCount',
  rdpFinancePageListUserPrepays: '/rdp/console/api/v1/finance/pageListUserPrepays',
  rdpFinanceCancelPrepay: '/rdp/console/api/v1/finance/cancelPrepay'
};
