/*
 * Copyright 2026 杭州开云集致科技有限公司
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.clougence.clouddm.base.metadata.ui;

/**
 * @author mode 2020/11/6 18:52
 */
public interface DsFeatureIDs {

    // FUNCTION
    String FUNC_RULE_CHECK_SUPPORT           = "FUNC_RULE_CHECK_SUPPORT";
    String FUNC_LINES_SUPPORT                = "FUNC_LINES_SUPPORT";

    // MENU
    String MENU_SEPARATOR                    = "MENU_SEPARATOR";
    String MENU_BROWSE_CONSOLE               = "MENU_BROWSE_CONSOLE";
    String MENU_BROWSE_REFRESH               = "MENU_BROWSE_REFRESH";
    String MENU_BROWSE_COPY_NAME             = "MENU_BROWSE_COPY_NAME";
    String MENU_BROWSE_COPY_JDBC             = "MENU_BROWSE_COPY_JDBC";
    String MENU_BROWSE_PROPERTY              = "MENU_BROWSE_PROPERTY";
    String MENU_BROWSE_PERMISSIONS           = "MENU_BROWSE_PERMISSIONS";
    //
    String MENU_BROWSE_INSTANCE_CREATE       = "MENU_BROWSE_INSTANCE_CREATE";
    String MENU_BROWSE_INSTANCE_DROP         = "MENU_BROWSE_INSTANCE_DROP";
    String MENU_BROWSE_INSTANCE_RENAME       = "MENU_BROWSE_INSTANCE_RENAME";
    //
    String MENU_BROWSE_CATALOG_CREATE        = "MENU_BROWSE_CATALOG_CREATE";
    String MENU_BROWSE_CATALOG_DROP          = "MENU_BROWSE_CATALOG_DROP";
    String MENU_BROWSE_CATALOG_RENAME        = "MENU_BROWSE_CATALOG_RENAME";
    //
    String MENU_BROWSE_SCHEMA_CREATE         = "MENU_BROWSE_SCHEMA_CREATE";
    String MENU_BROWSE_SCHEMA_DROP           = "MENU_BROWSE_SCHEMA_DROP";
    String MENU_BROWSE_SCHEMA_RENAME         = "MENU_BROWSE_SCHEMA_RENAME";
    //
    String MENU_BROWSE_TABLE_CREATE          = "MENU_BROWSE_TABLE_CREATE";
    String MENU_BROWSE_TABLE_ALTER           = "MENU_BROWSE_TABLE_ALTER";
    String MENU_BROWSE_TABLE_DROP            = "MENU_BROWSE_TABLE_DROP";
    String MENU_BROWSE_TABLE_RENAME          = "MENU_BROWSE_TABLE_RENAME";
    String MENU_BROWSE_TABLE_TRUNCATE        = "MENU_BROWSE_TABLE_TRUNCATE";
    String MENU_BROWSE_TABLE_DATA            = "MENU_BROWSE_TABLE_DATA";
    String MENU_BROWSE_TABLE_FAKER           = "MENU_BROWSE_TABLE_FAKER";
    String MENU_BROWSE_TABLE_FAKER_INCREMENT = "MENU_BROWSE_TABLE_FAKER_INCREMENT";
    String MENU_BROWSE_TABLE_IMPORT          = "MENU_BROWSE_TABLE_IMPORT";
    String MENU_BROWSE_TABLE_EXPORT          = "MENU_BROWSE_TABLE_EXPORT";
    String MENU_BROWSE_TABLE_REQUEST         = "MENU_BROWSE_TABLE_REQUEST";
    String MENU_BROWSE_TABLE_GENERATE        = "MENU_BROWSE_TABLE_GENERATE";
    String MENU_BROWSE_TABLE_GET_DDL         = "MENU_BROWSE_TABLE_GET_DDL";
    //
    String MENU_BROWSE_VIEW_CREATE           = "MENU_BROWSE_VIEW_CREATE";
    String MENU_BROWSE_VIEW_ALTER            = "MENU_BROWSE_VIEW_ALTER";
    String MENU_BROWSE_VIEW_DROP             = "MENU_BROWSE_VIEW_DROP";
    String MENU_BROWSE_VIEW_RENAME           = "MENU_BROWSE_VIEW_RENAME";
    String MENU_BROWSE_VIEW_DATA             = "MENU_BROWSE_VIEW_DATA";
    String MENU_BROWSE_VIEW_EXPORT           = "MENU_BROWSE_VIEW_EXPORT";
    String MENU_BROWSE_VIEW_REQUEST          = "MENU_BROWSE_VIEW_REQUEST";
    String MENU_BROWSE_VIEW_COMPILE          = "MENU_BROWSE_VIEW_COMPILE";
    //
    String MENU_BROWSE_MATERIALIZED_DROP     = "MENU_BROWSE_MATERIALIZED_DROP";
    String MENU_BROWSE_MATERIALIZED_REQUEST  = "MENU_BROWSE_MATERIALIZED_REQUEST";
    //
    String MENU_BROWSE_DBLINK_CREATE         = "MENU_BROWSE_DBLINK_CREATE";
    String MENU_BROWSE_DBLINK_TEST           = "MENU_BROWSE_DBLINK_TEST";
    String MENU_BROWSE_DBLINK_DROP           = "MENU_BROWSE_DBLINK_DROP";
    //
    String MENU_BROWSE_JOB_CREATE            = "MENU_BROWSE_JOB_CREATE";
    String MENU_BROWSE_JOB_ALTER             = "MENU_BROWSE_JOB_ALTER";
    String MENU_BROWSE_JOB_DROP              = "MENU_BROWSE_JOB_DROP";
    String MENU_BROWSE_JOB_DISABLE           = "MENU_BROWSE_JOB_DISABLE";
    String MENU_BROWSE_JOB_ENABLE            = "MENU_BROWSE_JOB_ENABLE";
    String MENU_BROWSE_JOB_RUN               = "MENU_BROWSE_JOB_RUN";
    //
    String MENU_BROWSE_SCHEDULE_CREATE       = "MENU_BROWSE_SCHEDULE_CREATE";
    String MENU_BROWSE_SCHEDULE_DROP         = "MENU_BROWSE_SCHEDULE_DROP";
    String MENU_BROWSE_SCHEDULE_DISABLE      = "MENU_BROWSE_SCHEDULE_DISABLE";
    String MENU_BROWSE_SCHEDULE_ENABLE       = "MENU_BROWSE_SCHEDULE_ENABLE";
    String MENU_BROWSE_SCHEDULE_RUN          = "MENU_BROWSE_SCHEDULE_RUN";
    String MENU_BROWSE_SCHEDULE_PROPERTY     = "MENU_BROWSE_SCHEDULE_PROPERTY";
    //
    String MENU_BROWSE_COLUMN_CREATE         = "MENU_BROWSE_COLUMN_CREATE";
    String MENU_BROWSE_COLUMN_RENAME         = "MENU_BROWSE_COLUMN_RENAME";
    String MENU_BROWSE_COLUMN_ALTER          = "MENU_BROWSE_COLUMN_ALTER";
    String MENU_BROWSE_COLUMN_TRUNCATE       = "MENU_BROWSE_COLUMN_TRUNCATE";
    String MENU_BROWSE_COLUMN_DROP           = "MENU_BROWSE_COLUMN_DROP";
    String MENU_BROWSE_COLUMN_GENERATE       = "MENU_BROWSE_COLUMN_GENERATE";
    //
    String MENU_BROWSE_PRIMARY_CREATE        = "MENU_BROWSE_PRIMARY_CREATE";
    String MENU_BROWSE_PRIMARY_RENAME        = "MENU_BROWSE_PRIMARY_RENAME";
    String MENU_BROWSE_PRIMARY_ALTER         = "MENU_BROWSE_PRIMARY_ALTER";
    String MENU_BROWSE_PRIMARY_DROP          = "MENU_BROWSE_PRIMARY_DROP";
    String MENU_BROWSE_PRIMARY_GENERATE      = "MENU_BROWSE_PRIMARY_GENERATE";
    //
    String MENU_BROWSE_INDEX_CREATE          = "MENU_BROWSE_INDEX_CREATE";
    String MENU_BROWSE_INDEX_RENAME          = "MENU_BROWSE_INDEX_RENAME";
    String MENU_BROWSE_INDEX_ALTER           = "MENU_BROWSE_INDEX_ALTER";
    String MENU_BROWSE_INDEX_DROP            = "MENU_BROWSE_INDEX_DROP";
    String MENU_BROWSE_INDEX_GENERATE        = "MENU_BROWSE_INDEX_GENERATE";
    //
    String MENU_BROWSE_PARTITION_CREATE      = "MENU_BROWSE_PARTITION_CREATE";
    String MENU_BROWSE_PARTITION_ALTER       = "MENU_BROWSE_PARTITION_ALTER";
    String MENU_BROWSE_PARTITION_DROP        = "MENU_BROWSE_PARTITION_DROP";
    String MENU_BROWSE_PARTITION_GENERATE    = "MENU_BROWSE_PARTITION_GENERATE";
    //
    String MENU_BROWSE_KEY_CREATE            = "MENU_BROWSE_KEY_CREATE";
    String MENU_BROWSE_KEY_DROP              = "MENU_BROWSE_KEY_DROP";
    String MENU_BROWSE_KEY_TRUNCATE          = "MENU_BROWSE_KEY_TRUNCATE";
    String MENU_BROWSE_KEY_DATA              = "MENU_BROWSE_KEY_DATA";
    String MENU_BROWSE_KEY_ALTER             = "MENU_BROWSE_KEY_ALTER";
    String MENU_BROWSE_KEY_RENAME            = "MENU_BROWSE_KEY_RENAME";
    String MENU_BROWSE_KEY_IMPORT            = "MENU_BROWSE_KEY_IMPORT";
    String MENU_BROWSE_KEY_EXPORT            = "MENU_BROWSE_KEY_EXPORT";
    //
    String MENU_BROWSE_TRIGGER_CREATE        = "MENU_BROWSE_TRIGGER_CREATE";
    String MENU_BROWSE_TRIGGER_DROP          = "MENU_BROWSE_TRIGGER_DROP";
    String MENU_BROWSE_TRIGGER_ALTER         = "MENU_BROWSE_TRIGGER_ALTER";
    String MENU_BROWSE_TRIGGER_COMPILE       = "MENU_BROWSE_TRIGGER_COMPILE";
    String MENU_BROWSE_TRIGGER_REQUEST       = "MENU_BROWSE_TRIGGER_REQUEST";
    //
    String MENU_BROWSE_PROCEDURE_DROP        = "MENU_BROWSE_PROCEDURE_DROP";
    String MENU_BROWSE_PROCEDURE_CREATE      = "MENU_BROWSE_PROCEDURE_CREATE";
    String MENU_BROWSE_PROCEDURE_ALTER       = "MENU_BROWSE_PROCEDURE_ALTER";
    String MENU_BROWSE_PROCEDURE_COMPILE     = "MENU_BROWSE_PROCEDURE_COMPILE";
    String MENU_BROWSE_PROCEDURE_REQUEST     = "MENU_BROWSE_PROCEDURE_REQUEST";
    //
    String MENU_BROWSE_SEQUENCE_DROP         = "MENU_BROWSE_SEQUENCE_DROP";
    //
    String MENU_BROWSE_SYNONYM_DROP          = "MENU_BROWSE_SYNONYM_DROP";
    String MENU_BROWSE_SYNONYM_REQUEST       = "MENU_BROWSE_SYNONYM_REQUEST";
    //
    String MENU_BROWSE_FUNCTION_DROP         = "MENU_BROWSE_FUNCTION_DROP";
    String MENU_BROWSE_FUNCTION_ALTER        = "MENU_BROWSE_FUNCTION_ALTER";
    String MENU_BROWSE_FUNCTION_CREATE       = "MENU_BROWSE_FUNCTION_CREATE";
    String MENU_BROWSE_FUNCTION_COMPILE      = "MENU_BROWSE_FUNCTION_COMPILE";
    String MENU_BROWSE_FUNCTION_REQUEST      = "MENU_BROWSE_FUNCTION_REQUEST";
    //
    String MENU_BROWSE_CONSTRAINT_ENABLE     = "MENU_BROWSE_CONSTRAINT_ENABLE";
    String MENU_BROWSE_CONSTRAINT_DISABLE    = "MENU_BROWSE_CONSTRAINT_DISABLE";
    //
    String MENU_BROWSE_USER_DROP             = "MENU_BROWSE_USER_DROP";
    String MENU_BROWSE_USER_CREATE           = "MENU_BROWSE_USER_CREATE";
}
