/*
 * Copyright 2026 杭州开云集致科技有限公司
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.clougence.clouddm.ds.redis.parser.ast;

import com.clougence.clouddm.ds.redis.parser.ast.CmdKindType;
import lombok.Getter;

public enum RedisCmdType {

    /* ----------------------------------------------------------------------------------- Keys commands */
    COPY("COPY", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    DEL("DEL", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    DUMP("DUMP", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    EXISTS("EXISTS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    EXPIRE("EXPIRE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    EXPIREAT("EXPIREAT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    EXPIRETIME("EXPIRETIME", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    KEYS("KEYS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    MOVE("MOVE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    OBJECT("OBJECT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    PERSIST("PERSIST", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    PEXPIRE("PEXPIRE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    PEXPIREAT("PEXPIREAT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    PEXPIRETIME("PEXPIRETIME", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    TTL("TTL", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    PTTL("PTTL", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    RANDOMKEY("RANDOMKEY", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    RENAME("RENAME", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    RENAMENX("RENAMENX", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    RESTORE("RESTORE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    SCAN("SCAN", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    SORT("SORT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    SORT_RO("SORT_RO", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    TOUCH("TOUCH", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    TYPE("TYPE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    UNLINK("UNLINK", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    /* ----------------------------------------------------------------------------------- String commands */
    APPEND("APPEND", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    DECR("DECR", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    DECRBY("DECRBY", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    GET("GET", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    GETDEL("GETDEL", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    GETEX("GETEX", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    GETRANGE("GETRANGE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    GETSET("GETSET", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    INCR("INCR", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    INCRBY("INCRBY", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    INCRBYFLOAT("INCRBYFLOAT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    LCS("LCS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    MGET("MGET", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    MSET("MSET", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    MSETNX("MSETNX", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    PSETEX("PSETEX", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    SET("SET", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    SETEX("SETEX", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    SETNX("SETNX", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    SETRANGE("SETRANGE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    STRLEN("STRLEN", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    SUBSTR("SUBSTR", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    /* ----------------------------------------------------------------------------------- Bit commands */
    BITCOUNT("BITCOUNT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    BITFIELD("BITFIELD", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    BITFIELD_RO("BITFIELD_RO", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    BITOP("BITOP", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    BITPOS("BITPOS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    GETBIT("GETBIT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    SETBIT("SETBIT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    /* ----------------------------------------------------------------------------------- Hash commands */
    HDEL("HDEL", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    HEXISTS("HEXISTS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    HEXPIRE("HEXPIRE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    HEXPIREAT("HEXPIREAT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    HEXPIRETIME("HEXPIRETIME", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    HGET("HGET", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    HGETALL("HGETALL", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    HGETDEL("HGETDEL", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    HGETEX("HGETEX", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    HINCRBY("HINCRBY", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    HINCRBYFLOAT("HINCRBYFLOAT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    HKEYS("HKEYS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    HLEN("HLEN", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    HMGET("HMGET", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    HMSET("HMSET", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    HPERSIST("HPERSIST", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    HPEXPIRE("HPEXPIRE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    HPEXPIREAT("HPEXPIREAT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    HPEXPIRETIME("HPEXPIRETIME", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    HPTTL("HPTTL", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    HTTL("HTTL", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    HRANDFIELD("HRANDFIELD", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    HSCAN("HSCAN", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    HSET("HSET", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    HSETEX("HSETEX", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    HSETNX("HSETNX", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    HSTRLEN("HSTRLEN", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    HVALS("HVALS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    /* ----------------------------------------------------------------------------------- List commands */
    BLMOVE("BLMOVE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write), // blocking
    BLMPOP("BLMPOP", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write), // blocking
    BLPOP("BLPOP", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write), // blocking
    BRPOP("BRPOP", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write), // blocking
    BRPOPLPUSH("BRPOPLPUSH", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write), // blocking
    LINDEX("LINDEX", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    LINSERT("LINSERT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    LLEN("LLEN", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    LMOVE("LMOVE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    LMPOP("LMPOP", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    LPOP("LPOP", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    LPOS("LPOS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    LPUSH("LPUSH", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    LPUSHX("LPUSHX", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    LRANGE("LRANGE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    LREM("LREM", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    LSET("LSET", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    LTRIM("LTRIM", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    RPOP("RPOP", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    RPOPLPUSH("RPOPLPUSH", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    RPUSH("RPUSH", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    RPUSHX("RPUSHX", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    /* ----------------------------------------------------------------------------------- Set commands */
    SADD("SADD", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    SCARD("SCARD", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    SDIFF("SDIFF", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    SDIFFSTORE("SDIFFSTORE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    SINTER("SINTER", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    SINTERCARD("SINTERCARD", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    SINTERSTORE("SINTERSTORE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    SISMEMBER("SISMEMBER", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    SMEMBERS("SMEMBERS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    SMISMEMBER("SMISMEMBER", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    SMOVE("SMOVE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    SPOP("SPOP", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    SRANDMEMBER("SRANDMEMBER", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    SREM("SREM", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    SSCAN("SSCAN", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    SUNION("SUNION", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    SUNIONSTORE("SUNIONSTORE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    /* ----------------------------------------------------------------------------------- sorted set commands */
    BZMPOP("BZMPOP", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write), // blocking
    BZPOPMAX("BZPOPMAX", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write), // blocking
    BZPOPMIN("BZPOPMIN", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write), // blocking
    ZADD("ZADD", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    ZCARD("ZCARD", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    ZCOUNT("ZCOUNT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    ZDIFF("ZDIFF", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    ZDIFFSTORE("ZDIFFSTORE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    ZINCRBY("ZINCRBY", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    ZINTER("ZINTER", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    ZINTERCARD("ZINTERCARD", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    ZINTERSTORE("ZINTERSTORE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    ZLEXCOUNT("ZLEXCOUNT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    ZMPOP("ZMPOP", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    ZMSCORE("ZMSCORE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    ZPOPMAX("ZPOPMAX", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    ZPOPMIN("ZPOPMIN", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    ZRANDMEMBER("ZRANDMEMBER", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    ZRANGE("ZRANGE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    ZRANGEBYLEX("ZRANGEBYLEX", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    ZRANGEBYSCORE("ZRANGEBYSCORE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    ZRANGESTORE("ZRANGESTORE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    ZRANK("ZRANK", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    ZREM("ZREM", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    ZREMRANGEBYLEX("ZREMRANGEBYLEX", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    ZREMRANGEBYRANK("ZREMRANGEBYRANK", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    ZREMRANGEBYSCORE("ZREMRANGEBYSCORE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    ZREVRANGE("ZREVRANGE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    ZREVRANGEBYLEX("ZREVRANGEBYLEX", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    ZREVRANGEBYSCORE("ZREVRANGEBYSCORE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    ZREVRANK("ZREVRANK", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    ZSCAN("ZSCAN", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    ZSCORE("ZSCORE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    ZUNION("ZUNION", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    ZUNIONSTORE("ZUNIONSTORE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    /* ----------------------------------------------------------------------------------- script commands */
    SCRIPT_DEBUG("SCRIPT DEBUG", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Script),
    SCRIPT_EXISTS("SCRIPT EXISTS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Script),
    SCRIPT_FLUSH("SCRIPT FLUSH", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Script),
    SCRIPT_KILL("SCRIPT KILL", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Script),
    SCRIPT_LOAD("SCRIPT LOAD", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Script),
    EVAL("EVAL", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Script),
    EVAL_RO("EVAL_RO", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Script),
    EVALSHA("EVALSHA", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Script),
    EVALSHA_RO("EVALSHA_RO", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Script),
    FCALL("FCALL", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Script),
    FCALL_RO("FCALL_RO", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Script),
    FUNCTION_DEL("FUNCTION DELETE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Script),
    FUNCTION_DUMP("FUNCTION DUMP", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Script),
    FUNCTION_FLUSH("FUNCTION FLUSH", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Script),
    FUNCTION_KILL("FUNCTION KILL", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Script),
    FUNCTION_LIST("FUNCTION LIST", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Script),
    FUNCTION_LOAD("FUNCTION LOAD", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Script),
    FUNCTION_RESTORE("FUNCTION RESTORE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Script),
    FUNCTION_STATS("FUNCTION STATS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Script),
    /* ----------------------------------------------------------------------------------- HyperLog commands */
    PFADD("PFADD", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    PFCOUNT("PFCOUNT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    PFMERGE("PFMERGE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Write),
    /* ----------------------------------------------------------------------------------- tx commands */
    DISCARD("DISCARD", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Transaction),
    EXEC("EXEC", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Transaction),
    MULTI("MULTI", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Transaction),
    UNWATCH("UNWATCH", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Transaction),
    WATCH("WATCH", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Transaction),
    /* ----------------------------------------------------------------------------------- publish commands */
    PSUBSCRIBE("PSUBSCRIBE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.PubSub),
    PUBLISH("PUBLISH", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.PubSub),
    PUBSUB_CHANNELS("PUBSUB CHANNELS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.PubSub),
    PUBSUB_NUMPAT("PUBSUB NUMPAT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.PubSub),
    PUBSUB_NUMSUB("PUBSUB NUMSUB", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.PubSub),
    PUBSUB_SHARDCHANNELS("PUBSUB SHARDCHANNELS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.PubSub),
    PUBSUB_SHARDNUMSUB("PUBSUB SHARDNUMSUB", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.PubSub),
    PUNSUBSCRIBE("PUNSUBSCRIBE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.PubSub),
    SPUBLISH("SPUBLISH", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.PubSub),
    SSUBSCRIBE("SSUBSCRIBE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.PubSub),
    SUBSCRIBE("SUBSCRIBE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.PubSub),
    SUNSUBSCRIBE("SUNSUBSCRIBE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.PubSub),
    UNSUBSCRIBE("UNSUBSCRIBE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.PubSub),
    /* ----------------------------------------------------------------------------------- cluster commands */
    ASKING("ASKING", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    READONLY("READONLY", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    READWRITE("READWRITE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    CLUSTER_ADDSLOTS("CLUSTER ADDSLOTS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLUSTER_ADDSLOTSRANGE("CLUSTER ADDSLOTSRANGE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLUSTER_BUMPEPOCH("CLUSTER BUMPEPOCH", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLUSTER_COUNT_FAILURE_REPORTS("CLUSTER COUNT-FAILURE-REPORTS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Monitor),
    CLUSTER_COUNTKEYSINSLOT("CLUSTER COUNTKEYSINSLOT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLUSTER_DELSLOTS("CLUSTER DELSLOTS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLUSTER_DELSLOTSRANGE("CLUSTER DELSLOTSRANGE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLUSTER_FAILOVER("CLUSTER FAILOVER", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLUSTER_FLUSHSLOTS("CLUSTER FLUSHSLOTS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLUSTER_FORGET("CLUSTER FORGET", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLUSTER_GETKEYSINSLOT("CLUSTER GETKEYSINSLOT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    CLUSTER_INFO("CLUSTER INFO", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    CLUSTER_KEYSLOT("CLUSTER KEYSLOT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    CLUSTER_LINKS("CLUSTER LINKS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLUSTER_MEET("CLUSTER MEET", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLUSTER_MYID("CLUSTER MYID", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    CLUSTER_MYSHARDID("CLUSTER MYSHARDID", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    CLUSTER_NODES("CLUSTER NODES", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    CLUSTER_REPLICAS("CLUSTER REPLICAS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLUSTER_REPLICATE("CLUSTER REPLICATE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLUSTER_RESET("CLUSTER RESET", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLUSTER_SAVECONFIG("CLUSTER SAVECONFIG", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLUSTER_SET_CONFIG_EPOCH("CLUSTER SET-CONFIG-EPOCH", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLUSTER_SETSLOT("CLUSTER SETSLOT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLUSTER_SHARDS("CLUSTER SHARDS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    CLUSTER_SLAVES("CLUSTER SLAVES", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLUSTER_SLOT_STATS("CLUSTER SLOT-STATS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    CLUSTER_SLOTS("CLUSTER SLOTS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    /* ----------------------------------------------------------------------------------- info commands */
    INFO("INFO", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Read),
    /* ----------------------------------------------------------------------------------- acl commands */
    ACL_CAT("ACL CAT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    ACL_DELUSER("ACL DELUSER", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    ACL_DRYRUN("ACL DRYRUN", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    ACL_GENPASS("ACL GENPASS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    ACL_GETUSER("ACL GETUSER", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    ACL_LIST("ACL LIST", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    ACL_LOAD("ACL LOAD", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    ACL_LOG("ACL LOG", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    ACL_SAVE("ACL SAVE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    ACL_SETUSER("ACL SETUSER", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    ACL_USERS("ACL USERS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    ACL_WHOAMI("ACL WHOAMI", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    /* -------------------------------------------------------------------------------- command commands */
    COMMAND("COMMAND", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    COMMAND_COUNT("COMMAND COUNT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    COMMAND_DOCS("COMMAND DOCS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    COMMAND_GETKEYS("COMMAND GETKEYS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    COMMAND_GETKEYSANDFLAGS("COMMAND GETKEYSANDFLAGS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    COMMAND_INFO("COMMAND INFO", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    COMMAND_LIST("COMMAND LIST", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    /* ----------------------------------------------------------------------------------- config commands */
    CONFIG_GET("CONFIG GET", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CONFIG_SET("CONFIG SET", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CONFIG_RESETSTAT("CONFIG RESETSTAT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CONFIG_REWRITE("CONFIG REWRITE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    /* ----------------------------------------------------------------------------------- latency commands */
    LATENCY_DOCTOR("LATENCY DOCTOR", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Monitor),
    LATENCY_GRAPH("LATENCY GRAPH", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Monitor),
    LATENCY_HISTOGRAM("LATENCY HISTOGRAM", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Monitor),
    LATENCY_HISTORY("LATENCY HISTORY", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Monitor),
    LATENCY_LATEST("LATENCY LATEST", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Monitor),
    LATENCY_RESET("LATENCY RESET", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    /* ----------------------------------------------------------------------------------- memory commands */
    MEMORY_DOCTOR("MEMORY DOCTOR", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Monitor),
    MEMORY_MALLOC_STATS("MEMORY MALLOC-STATS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Monitor),
    MEMORY_PURGE("MEMORY PURGE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    MEMORY_STATS("MEMORY STATS", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Monitor),
    MEMORY_USAGE("MEMORY USAGE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Monitor),
    /* ----------------------------------------------------------------------------------- module commands */
    MODULE_LIST("MODULE LIST", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    MODULE_LOAD("MODULE LOAD", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    MODULE_LOADEX("MODULE LOADEX", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    MODULE_UNLOAD("MODULE UNLOAD", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    /* ----------------------------------------------------------------------------------- control commands */
    BGREWRITEAOF("BGREWRITEAOF", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    BGSAVE("BGSAVE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    DBSIZE("DBSIZE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    FAILOVER("FAILOVER", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    FLUSHALL("FLUSHALL", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    FLUSHDB("FLUSHDB", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    LASTSAVE("LASTSAVE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    LOLWUT("LOLWUT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    MONITOR("MONITOR", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Monitor),
    PSYNC("PSYNC", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    REPLICAOF("REPLICAOF", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    ROLE("ROLE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    SAVE("SAVE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    SHUTDOWN("SHUTDOWN", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    SLAVEOF("SLAVEOF", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    SLOWLOG_GET("SLOWLOG GET", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Monitor),
    SLOWLOG_LEN("SLOWLOG LEN", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Monitor),
    SLOWLOG_RESET("SLOWLOG RESET", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    SWAPDB("SWAPDB", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    SYNC("SYNC", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    TIME("TIME", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    /* ----------------------------------------------------------------------------------- Client commands */
    CLIENT_CACHING("CLIENT CACHING", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    CLIENT_GETNAME("CLIENT GETNAME", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    CLIENT_GETREDIR("CLIENT GETREDIR", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    CLIENT_ID("CLIENT ID", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    CLIENT_INFO("CLIENT INFO", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    CLIENT_KILL("CLIENT KILL", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLIENT_LIST("CLIENT LIST", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLIENT_NO_EVICT("CLIENT NO-EVICT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLIENT_NO_TOUCH("CLIENT NO-TOUCH", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLIENT_PAUSE("CLIENT PAUSE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLIENT_REPLY("CLIENT REPLY", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLIENT_SETINFO("CLIENT SETINFO", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLIENT_SETNAME("CLIENT SETNAME", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLIENT_TRACKING("CLIENT TRACKING", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLIENT_TRACKINGINFO("CLIENT TRACKINGINFO", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLIENT_UNBLOCK("CLIENT UNBLOCK", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    CLIENT_UNPAUSE("CLIENT UNPAUSE", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    AUTH("AUTH", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    ECHO("ECHO", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    HELLO("HELLO", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    PING("PING", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    WAIT("WAIT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    WAITAOF("WAITAOF", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),
    QUIT("QUIT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    RESET("RESET", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Maintenance),
    SELECT("SELECT", com.clougence.clouddm.ds.redis.parser.ast.CmdKindType.Connection),;

    @Getter
    private final String                                        commandStr;
    @Getter
    private final com.clougence.clouddm.ds.redis.parser.ast.CmdKindType kindType;

    RedisCmdType(String commandStr, CmdKindType kindType){
        this.commandStr = commandStr;
        this.kindType = kindType;
    }

    public static RedisCmdType valueOfCode(String code) {
        for (RedisCmdType tableType : RedisCmdType.values()) {
            if (tableType.commandStr.equalsIgnoreCase(code)) {
                return tableType;
            }
        }
        throw new UnsupportedOperationException("Unsupported Redis command " + code);
    }
}
