##############################################################
##                                                   Server ##
##############################################################
server.port=8222
clouddm.rsocket.dns=127.0.0.1
clouddm.rsocket.console.port=8008
jwt.secret=jwt67843ad4s118123ycgve45uk12ghd3vli4u510fd9z35hec2hegre876n1g3sa8s2o
##############################################################
##                                               DataSource ##
##############################################################
spring.datasource.jdbcurl=jdbc:mysql://127.0.0.1:3306/cdmgr
spring.datasource.username=
spring.datasource.password=
##############################################################
##                                                DM Config ##
##############################################################
clougence.rdp.console.oppassword=false
clouddm.console.max-tx-session-user=20
console.config.cross.origins=*
