spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
spring.jackson.default-property-inclusion=non_null
#### logging
logging.level.root=info
logging.level.org.springframework.boot.autoconfigure=ERROR
logging.file.path=${app.logPath}
logging.file.name=${app.logPath}/sidecar.log
logging.config=classpath:logback.xml
spring.application.name=clouddm-worker-application
### prometheus config to monitor springboot application
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.application.name}
management.health.elasticsearch.enabled=false
