## sidecar
server.port=8223
app.mainModule=sidecar
app.logPath=logs/sidecar
#
#
#
dw.sidecar.session.max-count=5
dw.sidecar.tool-session.max-count=5
#
# console query sidecar limits.
dw.sidecar.online.max-queue=4000
dw.sidecar.online.max-executor=200
dw.sidecar.online.max-fetch-count=500
#
# export and async query sidecar limits.
dw.sidecar.export.max-queue=4000
dw.sidecar.export.max-executor=200
dw.sidecar.export.max-fetch-count=-1
