##############################################################
##                                                      Dev ##
##############################################################
spring.profiles.active=dev
app.mainModule=console
app.logPath=logs/console
clouddm.rsocket.printargs=true
clougence.rdp.deploy.env=dev
##############################################################
##                                                   Server ##
##############################################################
server.port=8222
clouddm.rsocket.dns=127.0.0.1
clouddm.rsocket.console.port=8008
jwt.secret=jwt67849ad4s118xd76dp8p49mbt64x5y3454p64gvli4u510f99z35hec2w8do876n1g3sa8s2o
##############################################################
##                                               DataSource ##
##############################################################
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.jdbcurl=jdbc:mysql://127.0.0.1:3306/cdmgr
spring.datasource.username=origin
spring.datasource.password=123258
##############################################################
##                                                DM Config ##
##############################################################
clougence.rdp.console.oppassword=false
clouddm.console.max-tx-session-user=20
clougence.rdp.login.reset.period.minuetes=1
console.config.cross.origins=*
editor.query.test=false
##############################################################
##                                                     Test ##
##############################################################
#clougence.rdp.deploy.context-path=http://dm-tongji.clougence.com/
#clougence.rdp.login.cookie.domain=dm-tongji.clougence.com
clouddm.upgrade.server=127.0.0.1:8113
