##############################################################
##                                                   Server ##
##############################################################
server.port=%APP_WEB_PORT%
jwt.secret=%APP_WEB_JWT%
server.tomcat.basedir=/opt/cgdm/alone/tmp
clouddm.rsocket.dns=%APP_SERVE_NAME%
clouddm.rsocket.console.port=%APP_SERVE_PORT%
##############################################################
##                                               DataSource ##
##############################################################
spring.datasource.jdbcurl=jdbc:mysql://%DB_HOST%:%DB_PORT%/%DB_DATABASE%?serverTimezone=Asia/Shanghai&characterEncoding=utf8&socketTimeout=30000&connectTimeout=3000
spring.datasource.username=%DB_USERNAME%
spring.datasource.password=%DB_PASSWORD%
##############################################################
##                                                      SMS ##
##############################################################
clougence.rdp.sms.verify_code=false
clougence.rdp.sms.aliyun.ak=
clougence.rdp.sms.aliyun.sk=
#clougence.rdp.config.sms.verify_code=false
#clougence.rdp.config.send.alert.ak=
#clougence.rdp.config.send.alert.sk=
##############################################################
##                                                      IM  ##
##############################################################
## dingtalk / weixin ##
clougence.rdp.alert.type=dingtalk
clougence.rdp.alert.dingtalk.alerturl=
clougence.rdp.alert.weixin.alerturl=
clougence.rdp.alert.slack.alerturl=
clougence.rdp.alert.discord.alerturl=
clougence.rdp.alert.feishu.alerturl=
clougence.rdp.alert.custom.alerturl=
clougence.rdp.alert.timeout.ms=5000
##############################################################
##                                               Aliyun OSS ##
##############################################################
clougence.rdp.api.aliyun.invpc=false
clougence.rdp.install.oss.special=false
clougence.rdp.install.oss.special.bucket=
clougence.rdp.install.oss.special.endpoint=
clougence.rdp.install.oss.ak=
clougence.rdp.install.oss.sk=
clouddm.install.aliyun.oss.download_site=https://download.clougence.com
clouddm.install.aliyun.oss.package=clouddm.tgz
clouddm.install.aliyun.oss.download_region=hangzhou
##############################################################
##                                                DM Config ##
##############################################################
clougence.rdp.console.oppassword=false
clougence.rdp.product.trial=true
clougence.rdp.product.trial.verify_code=777777
clouddm.console.max-tx-session-user=20
clougence.rdp.black.ds.self=Dameng,Hana,Redshift,Kafka,RocketMQ,RabbitMQ,AutoMQ,DeltaLake,Hive,ElasticSearch,Kudu,\
  Tunnel,Hudi,Lindorm,DocumentDB,Iceberg,Pulsar,GreptimeDB,TDengine,SshFile,LocalAI,RagApi,Ollama,DuckDB,Paimon,GoogleDrive,Yuque
clougence.rdp.black.ds.aliyun=ClickHouse,ElasticSearch,Greenplum,Kafka,RabbitMQ,RocketMQ,SQLServer,DashScope,DataLakeFormation,OssFile
clougence.rdp.black.ds.aws=AuroraMySQL,AuroraPostgreSQL,DocumentDB,MariaDB,Oracle,Redshift,SQLServer,S3File,Bedrock,ElastiCache,AmazonMSK,DynamoDB
clougence.rdp.black.ds.azure=MariaDB,SQLServer
clougence.rdp.black.ds.huawei=GaussDBForMySQL,
clougence.rdp.black.ds.independent=OpenAI,HuggingFace,Cohere,DeepSeek
clougence.rdp.black.deploy=HUAWEI_CLOUD_HOSTED,INDEPENDENT_CLOUD_PLATFORM,TENCENT_CLOUD_HOSTED
clougence.rdp.login.reset.period.minuetes=1
clougence.rdp.user.autoreset_pwd=test@clougence.com:clougence2021
console.config.cross.origins=*
editor.query.test=false
clouddm.authcode.userlimit=10
clouddm.authcode.dslimit=10
##############################################################
##                                                  sidecar ##
##############################################################
dw.sidecar.session.max-count=5
dw.sidecar.tool-session.max-count=5
# console query sidecar limits.
dw.sidecar.online.max-queue=4000
dw.sidecar.online.max-executor=200
dw.sidecar.online.max-fetch-count=500
# export and async query sidecar limits.
dw.sidecar.export.max-queue=4000
dw.sidecar.export.max-executor=200
dw.sidecar.export.max-fetch-count=-1
##############################################################
##                                                     Test ##
##############################################################
#clougence.rdp.deploy.context-path=http://dm-tongji.clougence.com/
#clougence.rdp.login.cookie.domain=dm-tongji.clougence.com
clouddm.upgrade.server=127.0.0.1:8113
