##############################################################
##                                                   Server ##
##############################################################
server.port=%APP_WEB_PORT%
jwt.secret=%APP_WEB_JWT%
server.tomcat.basedir=/opt/cgdm/console/tmp
clouddm.rsocket.dns=%APP_SERVE_NAME%
clouddm.rsocket.console.port=%APP_SERVE_PORT%
##############################################################
##                                               DataSource ##
##############################################################
spring.datasource.jdbcurl=jdbc:mysql://%DB_HOST%:%DB_PORT%/%DB_DATABASE%
spring.datasource.username=%DB_USERNAME%
spring.datasource.password=%DB_PASSWORD%
##############################################################
##                                                DM Config ##
##############################################################
clougence.rdp.console.oppassword=false
clouddm.console.max-tx-session-user=20
console.config.cross.origins=*
